server:
    port: 8080
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot_dubbo?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: root
        password:
        # 连接初始值，连接池启动时创建的连接数量的初始值
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    dubbo:
        application:
            name: dubbo-provider # 本服务的名称
        registry:
            address: zookeeper://192.168.168.135:2181 # ZooKeeper所在服务器的IP和端口号
        protocol:
            name: dubbo # RPC通信所采用的协议
            port: 20880 # 本服务对外暴露的端口号
        scan: com.lcz.dubbo.service # 服务实现类所在的路径
# mybatis
mybatis:
    mapperLocations: classpath:mapper/*.xml
    # configLocation: classpath:mybatis.xml
    configuration:
        # 开启驼峰转换
        map-underscore-to-camel-case: true