server:
    port: 8081

spring:
    dubbo:
        application:
            name: dubbo-consumer # 服务名称
        registry:
            address: zookeeper://192.168.178.136:2181 # zookeeper所在服务器的IP和端口号
        scan: com.lcz.dubbo.controller # 引用服务的路径